-- CRIAÇÃO DAS TABELAS


CREATE TABLE CONTAS(
    NUMERO INTEGER NOT NULL,
    SALDO DECIMAL (8,2),
    TITULAR VARCHAR (200),
    CONSTRAINT CLIENTES_PK PRIMARY KEY(NUMERO)

);

-- CONSULTAR CONTEUDO DA TABELA

SELECT *
FROM CONTAS;

-- INSERINDO REGISTROS NA TABELA CONTAS

INSERT INTO CONTAS(NUMERO, SALDO, TITULAR)
VALUES(123, 9999.99, 'ASDRUBAL' );